"""Add gender field to User model

Revision ID: cdab75ba8196
Revises: 
Create Date: 2023-12-04 13:25:32.396490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdab75ba8196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=10), server_default='Male', nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('phone_no', sa.String(length=15), nullable=True),
    sa.Column('primary_address', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.CheckConstraint("gender IN ('Male', 'Female', 'Others')", name='check_gender'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
